services:
  blooddonation.apis:
    image: blooddonation.apis
    build:
      context: .
      dockerfile: BloodDonation.Apis/Dockerfile
    ports:
      - "5152:8080"
      - "7165:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
  
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      - POSTGRES_DB=blood_donation
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  seq:
    image: datalust/seq:2024.3
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "8081:80"